### ISSUE TITLE
Volume adjust

### ISSUE THREAD

**Issue by coelho-oliva** [gcushen/spotify-rise#2]
I'd like to know how to(if there's a way) define the starting point of the volume. If not, would you, please, consider coding that?

Thanks!

**Comment by gcushen** [comment]
I'm not sure what the use case is for the alarm volume to start at a higher level during the fade in process because generally the point of fading in a song is to start from a very low volume? Or are you after an option to completely remove the fade in and start at the default volume level? Or an option to define the main volume at the end of the fade in?

It's simple to change the starting level, if that's what you really want. At approx line 106 of the script, simply change `volume = 0` to any value less than `65536`:

```
for ((volume = 0; volume <= 65536; volume += 3250)); do
```

For example, this should start at about half your max volume:

```
for ((volume = 33000; volume <= 65536; volume += 3250)); do
```

Otherwise, if you want to change the main volume of the alarm, simple decrease 65536 in `volume <= 65536`.
